name: MyAmaysim Test Automation exercise pipeline
on: [push]

jobs:
  testMobile:
    name: Mobile Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Lint
        run: npx eslint cypress/e2e/*.spec.cy.js
      - name: TestMobile
        run: npx cypress run
      - name: UploadArtifacts
        uses: actions/upload-artifact@v1
        with:
          name: Screenshots and Videos
          path: cypress/videos cypress/screenshots