name: MyAmaysim Test Automation exercise pipeline
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Lint
        run: npx eslint cypress/e2e/*.spec.cy.js

  testLinuxElectron:
    name: Run tests on a Ubuntu environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Cypress run
        run: npx cypress run
      - name: UploadArtifacts
        uses: actions/upload-artifact@v1
        with:
          name: Screenshots and Videos
          path: cypress/videos cypress/screenshots